// VOR: One-command OpenClaw provisioning
// `vibe companion setup` detects existing OpenClaw. If none:
//   (A) Deploy to Railway (one-click template, ~60s)
//   (B) Docker compose locally
//   (C) Connect existing
// Option A auto-provisions VPS with OpenClaw + VoR skills.

/**
 * Minimum compatible OpenClaw version for VoR skills.
 */
const MIN_OPENCLAW_VERSION = "0.5.0";

/**
 * Railway template URL for one-click OpenClaw deployment.
 */
const RAILWAY_TEMPLATE_URL = "https://railway.app/template/openclaw-vor";

/**
 * Represents a detected or connected OpenClaw instance.
 */
export interface OpenClawInstance {
  url: string;
  version: string;
  skills: string[];
}

/**
 * Result of OpenClaw detection.
 */
export interface DetectionResult {
  found: boolean;
  url?: string;
  version?: string;
}

/**
 * Result of Railway provisioning.
 */
export interface RailwayProvisionResult {
  method: "railway";
  templateUrl: string;
  instructions: string[];
  estimatedSeconds: number;
}

/**
 * Result of Docker provisioning.
 */
export interface DockerProvisionResult {
  method: "docker";
  composeContent: string;
  instructions: string[];
}

/**
 * Docker provisioning options.
 */
export interface DockerOptions {
  projectName: string;
  port?: number;
}

/**
 * Result of connecting to an existing instance.
 */
export interface ConnectionResult {
  connected: boolean;
  instance?: OpenClawInstance;
  error?: string;
}

/**
 * Result of skill installation.
 */
export interface SkillInstallResult {
  installed: string[];
  failed: string[];
}

/**
 * Skill installation options.
 */
export interface InstallSkillsOptions {
  skills: string[];
  fetcher?: typeof fetch;
}

/**
 * Union of all provisioning results.
 */
export type ProvisionResult = RailwayProvisionResult | DockerProvisionResult;

/**
 * Fetcher type for dependency injection in tests.
 */
type Fetcher = (
  url: string,
  init?: RequestInit,
) => Promise<{
  ok: boolean;
  status?: number;
  json: () => Promise<unknown>;
}>;

// ---------------------------------------------------------------------------
// Version comparison
// ---------------------------------------------------------------------------

function isVersionCompatible(version: string, minVersion: string): boolean {
  const parse = (v: string) => v.split(".").map(Number);
  const current = parse(version);
  const minimum = parse(minVersion);

  for (let i = 0; i < 3; i++) {
    const c = current[i] ?? 0;
    const m = minimum[i] ?? 0;
    if (c > m) return true;
    if (c < m) return false;
  }
  return true; // equal
}

// ---------------------------------------------------------------------------
// Detection
// ---------------------------------------------------------------------------

/**
 * Detect if an OpenClaw instance is running at the given URL.
 */
export async function detectOpenClaw(
  url: string,
  fetcher?: Fetcher,
): Promise<DetectionResult> {
  const fetchFn = fetcher ?? (globalThis.fetch as unknown as Fetcher);

  try {
    const response = await fetchFn(`${url}/api/status`);
    if (!response.ok) {
      return { found: false };
    }

    const data = (await response.json()) as {
      version: string;
      status: string;
      skills: string[];
    };

    return {
      found: true,
      url,
      version: data.version,
    };
  } catch {
    return { found: false };
  }
}

// ---------------------------------------------------------------------------
// Railway Provisioning
// ---------------------------------------------------------------------------

/**
 * Generate Railway deployment instructions for OpenClaw.
 * One-click template that provisions OpenClaw + VoR skills in ~60s.
 */
export async function provisionRailway(): Promise<RailwayProvisionResult> {
  return {
    method: "railway",
    templateUrl: RAILWAY_TEMPLATE_URL,
    instructions: [
      "1. Click the Railway template link to deploy OpenClaw",
      "2. Connect your GitHub account if prompted",
      "3. Railway will provision the instance (~60 seconds)",
      "4. Copy the deployment URL from Railway dashboard",
      "5. Run: vibe companion connect <railway-url>",
    ],
    estimatedSeconds: 60,
  };
}

// ---------------------------------------------------------------------------
// Docker Provisioning
// ---------------------------------------------------------------------------

/**
 * Generate Docker Compose configuration for local OpenClaw deployment.
 */
export async function provisionDocker(
  options: DockerOptions,
): Promise<DockerProvisionResult> {
  const port = options.port ?? 3100;

  const composeContent = `# OpenClaw + VoR Companion — Docker Compose
# Generated by: vibe companion setup docker
# Project: ${options.projectName}

version: "3.8"

services:
  openclaw:
    image: openclaw/openclaw:latest
    container_name: ${options.projectName}-openclaw
    ports:
      - "${port}:3100"
    environment:
      - OPENCLAW_PORT=3100
      - OPENCLAW_DATA_DIR=/data
    volumes:
      - openclaw-data:/data
    restart: unless-stopped

volumes:
  openclaw-data:
    driver: local
`;

  return {
    method: "docker",
    composeContent,
    instructions: [
      "1. Save the docker-compose.yml to your project root",
      `2. Run: docker compose up -d`,
      `3. OpenClaw will be available at http://localhost:${port}`,
      `4. Run: vibe companion connect http://localhost:${port}`,
    ],
  };
}

// ---------------------------------------------------------------------------
// Connect Existing
// ---------------------------------------------------------------------------

/**
 * Connect to an existing OpenClaw instance.
 * Validates the instance is reachable and version-compatible.
 */
export async function connectExisting(
  url: string,
  fetcher?: Fetcher,
): Promise<ConnectionResult> {
  const fetchFn = fetcher ?? (globalThis.fetch as unknown as Fetcher);

  try {
    const response = await fetchFn(`${url}/api/status`);
    if (!response.ok) {
      return {
        connected: false,
        error: "Could not connect to OpenClaw instance",
      };
    }

    const data = (await response.json()) as {
      version: string;
      status: string;
      skills: string[];
    };

    if (!isVersionCompatible(data.version, MIN_OPENCLAW_VERSION)) {
      return {
        connected: false,
        error: `OpenClaw version ${data.version} is incompatible. Minimum required: ${MIN_OPENCLAW_VERSION}. Please upgrade OpenClaw.`,
      };
    }

    return {
      connected: true,
      instance: {
        url,
        version: data.version,
        skills: data.skills,
      },
    };
  } catch {
    return {
      connected: false,
      error: "Could not connect to OpenClaw instance",
    };
  }
}

// ---------------------------------------------------------------------------
// Skill Installation
// ---------------------------------------------------------------------------

/**
 * Install VoR skills into an OpenClaw instance.
 */
export async function installSkills(
  instance: OpenClawInstance,
  options: InstallSkillsOptions,
): Promise<SkillInstallResult> {
  const fetchFn = options.fetcher ?? (globalThis.fetch as unknown as Fetcher);
  const installed: string[] = [];
  const failed: string[] = [];

  for (const skill of options.skills) {
    try {
      const response = await fetchFn(`${instance.url}/api/skills/install`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ skill }),
      });

      if (response.ok) {
        installed.push(skill);
      } else {
        failed.push(skill);
      }
    } catch {
      failed.push(skill);
    }
  }

  return { installed, failed };
}
